# -*- coding: utf-8 -*-
"""“Heatmaps of models on AD-CN tasks on ADNI.ipynb”的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bk96ClNEn-F21OUevoZ5yQj57VJPg13I

# 3D Heatmap Visualization in Anatomical Planes

This Google Colab notebook provides an interactive interface for visualizing 3D heatmaps in multiple anatomical planes (transverse/axial, coronal, and sagittal).
The slice coordinate range is [0, 150]. Detailed explanations of the models and visualization methods are available in the paper.

## Orientation (MNI space)
- x-axis: left (–) ↔ right (+)
- y-axis: posterior (–) ↔ anterior (+)
- z-axis: inferior (–) ↔ superior (+)

## Within a Single Slice
- Axial (fixed z): the vertical image axis corresponds to y (upward = posterior → anterior).
- Coronal (fixed y): the vertical image axis corresponds to z (upward = inferior → superior).

## Across Slices
- Moving from back to front across coronal slices corresponds to increasing y.
- Moving from bottom to top across axial slices corresponds to increasing z.

## Heatmap Type
The heatmap for the VBM-SVM model represents a p-map (thresholded at p = 0.05 → 0), while the other heatmaps are w-maps.



# 3D Heatmap Visualization in Anatomical Planes

This Google Colab notebook provides an interactive interface for visualizing 3D heatmaps in multiple anatomical planes (axial, coronal, and sagittal).

👉 Colab link:  
https://colab.research.google.com/drive/1ULK1Utmp90f9NvWgjuCdKG_jzQzStYvJ?usp=sharing  

👉 Colab link:  
https://gitlab.com/radiology/neuro/gl-icnn


⚠️ Note: Please scroll down to access the interactive visualizations.  
Some warnings at the top of the notebook can be safely ignored.

The slice coordinate range is [0, 150]. Detailed descriptions of the models and visualization methods can be found in the associated paper.

## Orientation (MNI Space)

- x-axis: left (–) ↔ right (+)  
- y-axis: posterior (–) ↔ anterior (+)  
- z-axis: inferior (–) ↔ superior (+)

## Slice Interpretation

### Within a Single Slice

- Axial (fixed z): the vertical axis corresponds to y (posterior → anterior)
- Coronal (fixed y): the vertical axis corresponds to z (inferior → superior)

### Across Slices

- Moving across coronal slices (back → front) corresponds to increasing y  
- Moving across axial slices (bottom → top) corresponds to increasing z  

## Heatmap Types

- VBM-SVM: heatmap represents a p-map, thresholded at p = 0.05 (values below threshold set to 0)  
- Other models: heatmaps represent w-maps (model-derived feature contribution weights)
"""

### A simple display for the visualization of models:
![My GIF](https://drive.google.com/file/d/1snze-ahge0UvjiiPoFjI21C3hDc9s9Ld/view?usp=drive_link)

import nibabel as nib
import math
import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.gridspec import GridSpec
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
from scipy import ndimage
from scipy.ndimage import gaussian_filter
import ipywidgets as widgets
from ipywidgets import interactive_output
from ipywidgets import GridBox, Layout, Output
from IPython.display import display,Image

###Load data

!gdown --id 1kHQlVTazUwTMSeGzrT3kgfsG-lM6LNuA -O /content/aparcaseg_in_MNI.nii.gz
!gdown --id 14ls7KNATP1P3eTokGOQB7VxJ-AeCiEei -O /content/ICNN_ADCN_ADNI.npy
!gdown --id 1_QoODC4r3oilIDfDZY-G-Ov3H_8YogoB -O /content/VolEBM_ADCN_ADNI.npy
!gdown --id 1hqCSFUkAg_7sn72JCr8Yx0yJMVYGjocx -O /content/VGG_OCC_ADCN_ADNI.npy
!gdown --id 1m2Iq26iWcA54FnI1qk9WdezX8duvikCa -O /content/DenseNet_OCC_ADCN_ADNI.npy
!gdown --id 1KEqAiwch8ihgjm80k8ficWgVN76Cr33F -O /content/VolSVM_wmap_ADCN_ADNI.npy
!gdown --id 1jghVvwtRqWPTMLGnJG4eUQ-b8BzIQi2J -O /content/VBMSVM_pmap_ADCN_ADNI.npy
!gdown --id 1OOcL-gs4Y-gFsP6sFW6AoWew1wVyXt5l -O /content/GLCNN_OCC_ADCN_ADNI.npy
!gdown --id 1cSKI0BCDCfelkgt6Pl9nOFHAj03kFLVS -O /content/ICNN-IGANN_ADCN_ADNI.npy
!gdown --id 1YYNv7tQlGrOWxdjRrDqrKtL_stf93whC -O /content/ICNN-NAM_ADCN_ADNI.npy
!gdown --id 14mYpDnXoVrQW0LxCY_A7ejPQBnsHtnFH -O /content/ConvNext_OCC_ADCN_ADNI.npy
!gdown --id 14mYpDnXoVrQW0LxCY_A7ejPQBnsHtnFH -O /content/ConvNext_OCC_ADCN_ADNI.npy
!gdown --id 1FF8bQb38ayOAoui31meoRBVJlA0KeIDK -O /content/T1brain_in_MNI.nii.gz

###Functions to plot the heatmaps
from scipy.ndimage import gaussian_filter, label, generate_binary_structure
def remove_single_voxels(binary_mask, connectivity=1):
    """
    Remove isolated single-voxel clusters (size < 2).
    connectivity=1 -> 6-connected (3D).
    """
    structure = generate_binary_structure(3, connectivity)
    labeled, n = label(binary_mask, structure=structure)
    if n == 0:
        return binary_mask * 0
    sizes = np.bincount(labeled.ravel())
    keep = sizes >= 2
    keep[0] = False  # background
    clean = keep[labeled]
    return clean.astype(binary_mask.dtype)


def plot_selected_slices(struct_arr, num_slices=6, cmap='gray', vmin=None, vmax=None, overlay=None,
                         overlay_cmap='hot', overlay_vmin=None, overlay_vmax=None, _class=None, iteration=0):
    """
    Plot slices of a 3D image (and an overlay) along every axis, restricted to the middle 25%-75% region.
    """
    import matplotlib.pyplot as plt
    import numpy as np
    from scipy import ndimage
    from matplotlib.gridspec import GridSpec

    if vmin is None:
        vmin = struct_arr.min()
    if vmax is None:
        vmax = struct_arr.max()
    if overlay_vmin is None and overlay is not None:
        overlay_vmin = overlay.min()
    if overlay_vmax is None and overlay is not None:
        overlay_vmax = overlay.max()
    print(vmin, vmax, overlay_vmin, overlay_vmax)

    # Create the figure with GridSpec for precise control
    fig = plt.figure(figsize=(num_slices * 2, 6))
    gs = GridSpec(3, num_slices, figure=fig, wspace=0.05, hspace=0.02)  # Reduced hspace to minimize row spacing

    # Define slice indices for the middle 25%-75% range
    slice_ranges = []
    for axis in range(3):
        start = int(struct_arr.shape[axis] * 0.25)
        end = int(struct_arr.shape[axis] * 0.75)
        indices = np.linspace(start, end, num_slices, dtype=int)
        slice_ranges.append(indices)

    # Add the overlay colorbar (if overlay is provided)
    cbar_ax = None
    if overlay is not None:
        cbar_ax = fig.add_axes([0.92, 0.2, 0.015, 0.6])  # Adjusted colorbar position and size

    for axis, axis_label in zip([0, 1, 2], ['x', 'y', 'z']):
        for i in range(num_slices):
            ax = fig.add_subplot(gs[axis, i])  # Use GridSpec to position subplots
            i_slice = slice_ranges[axis][i]

            ax.axis('off')
            ax.imshow(ndimage.rotate(np.take(struct_arr, i_slice, axis=axis), 90),
                      vmin=vmin, vmax=vmax, cmap=cmap, interpolation=None)
            ax.text(0.03, 0.97, '{}={}'.format(axis_label, i_slice), color='white',
                    horizontalalignment='left', verticalalignment='top', transform=ax.transAxes)

            if overlay is not None:
                im = ax.imshow(ndimage.rotate(np.take(overlay, i_slice, axis=axis), 90),
                               cmap=overlay_cmap, vmin=overlay_vmin, vmax=overlay_vmax,
                               interpolation=None, alpha=0.7)

    # Add colorbar for the overlay
    if overlay is not None:
        fig.colorbar(im, cax=cbar_ax)

    # Save the plotted heatmap slice (optional; specify appropriate file path)
    plt.show()
    #plt.close(fig)



def plot_transverse_heatmaps(img_npy, heatmaps, z_coord, cmap='gray', vmin=None, vmax=None,
                             overlay_cmap='hot', overlay_vmin=None, overlay_vmax=None, max_cols=4):
    """
    Plot multiple heatmaps on a specified z slice, each with its own independent colorbar,
    and automatically wrap to a new row (with a maximum of max_cols plots per row).

    Parameters:
    - img_npy: 3D array (base anatomical image)
    - heatmaps: Dictionary {model_name: 3D heatmap array}
    - z_coord: Specified z slice to display
    - cmap: Colormap for the base image
    - vmin, vmax: Intensity range for the base image
    - overlay_cmap: Colormap for the overlay heatmaps
    - overlay_vmin, overlay_vmax: Intensity range for each heatmap (set independently)
    - max_cols: Maximum number of plots per row; if exceeded, new rows are created
    """
    num_models = len(heatmaps)

    # Calculate the number of columns and rows
    ncols = min(num_models, max_cols)
    nrows = math.ceil(num_models / ncols)

    # Create subplots; adjust the figsize as needed
    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * 3, nrows * 4), constrained_layout=True)

    # If there's only one subplot, axes is not an array, so convert it to a list
    if nrows * ncols == 1:
        axes = [axes]
    else:
        axes = axes.flatten()

    # Plotting for each model
    for i, (model_name, heatmap) in enumerate(heatmaps.items()):
        ax = axes[i]
        ax.axis('off')

        # Calculate local vmin/vmax for the current heatmap
        local_vmin = overlay_vmin if overlay_vmin is not None else heatmap.min()
        local_vmax = overlay_vmax if overlay_vmax is not None else heatmap.max()

        # Plot the base anatomical image (rotated 90° to match the original orientation)
        ax.imshow(ndimage.rotate(img_npy[:, :, z_coord], 90), vmin=vmin, vmax=vmax, cmap=cmap, interpolation=None)
        ax.text(0.03, 0.97, f'{model_name}\n(z={z_coord})', color='white',
                horizontalalignment='left', verticalalignment='top', transform=ax.transAxes)

        # Plot the overlay heatmap
        im = ax.imshow(ndimage.rotate(heatmap[:, :, z_coord], 90), cmap=overlay_cmap,
                       vmin=local_vmin, vmax=local_vmax, interpolation=None, alpha=0.7)

        # Add an independent colorbar with correct scaling
        cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        cbar.ax.tick_params(labelsize=7)

    # If there are more subplots than models, turn off the extra axes
    for j in range(i + 1, nrows * ncols):
        axes[j].axis('off')

    plt.show()




def interactive_slider(img_npy, heatmaps, overlay_cmap='hot'):
    """
    Create an interactive slider to control the z slice dynamically,
    ensuring that each model has its own independent colorbar.

    Parameters:
    - img_npy: 3D base anatomical image
    - heatmaps: Dictionary {model_name: 3D heatmap array}
    - overlay_cmap: Colormap for heatmaps
    """
    max_z = img_npy.shape[2] - 1  # Max slice index
    z_slider = widgets.IntSlider(value=max_z // 2, min=0, max=max_z, step=1, description="Z Slice")

    # Output area
    output = widgets.Output()

    def update_plot(z_coord):
        with output:
            output.clear_output(wait=True)
            # Call function ensuring colorbars are independent and fixed
            plot_transverse_heatmaps(img_npy, heatmaps, z_coord, overlay_cmap=overlay_cmap)

    # Bind slider to function
    widgets.interactive(update_plot, z_coord=z_slider)

    # Display slider and output
    display(z_slider, output)

def plot_transverse_heatmaps_with_coronal(img_npy, heatmaps, z_coord, cmap='gray', vmin=None, vmax=None,
                                          overlay_cmap='hot', overlay_vmin=None, overlay_vmax=None, max_cols=4):
    """
    Plot multiple transverse heatmaps (at a specified z slice) for various models, each with its own colorbar,
    automatically wrapping to new rows (with a maximum of max_cols plots per row). Additionally, add a coronal view
    at the bottom with a horizontal red dashed line indicating the current transverse slice position.

    Parameters:
    - img_npy: 3D array representing the base anatomical image.
    - heatmaps: Dictionary {model_name: 3D heatmap array}.
    - z_coord: The transverse (z) slice to display.
    - cmap: Colormap for the base image.
    - vmin, vmax: Intensity range for the base image.
    - overlay_cmap: Colormap for the overlay heatmaps.
    - overlay_vmin, overlay_vmax: Intensity range for each overlay heatmap (set independently).
    - max_cols: Maximum number of plots per row; new rows are created if exceeded.
    """
    num_models = len(heatmaps)

    # Calculate the number of columns and rows for the heatmap grid.
    ncols = min(num_models, max_cols)
    nrows = math.ceil(num_models / ncols)

    # Total rows = heatmap grid rows + 1 extra row for the coronal view.
    total_rows = nrows + 1

    # Create the figure and GridSpec layout.
    fig = plt.figure(figsize=(ncols * 3, total_rows * 4), constrained_layout=True)
    gs = GridSpec(total_rows, ncols, figure=fig, wspace=0.05, hspace=0.3)

    # Create subplots for the heatmaps in the first nrows rows.
    axes = []
    for i in range(nrows * ncols):
        if i < num_models:
            ax = fig.add_subplot(gs[i // ncols, i % ncols])
            axes.append(ax)
        else:
            ax = fig.add_subplot(gs[i // ncols, i % ncols])
            ax.axis('off')
            axes.append(ax)

    # Plot each model's transverse heatmap.
    for i, (model_name, heatmap) in enumerate(heatmaps.items()):
        ax = axes[i]
        ax.axis('off')

        # Compute local vmin/vmax for the current heatmap.
        local_vmin = overlay_vmin if overlay_vmin is not None else heatmap.min()
        local_vmax = overlay_vmax if overlay_vmax is not None else heatmap.max()

        # Plot the base anatomical image's transverse slice (img_npy[:, :, z_coord]),
        # rotated 90° to maintain the correct orientation.
        ax.imshow(ndimage.rotate(img_npy[:, :, z_coord], 90), vmin=vmin, vmax=vmax, cmap=cmap, interpolation=None)
        ax.text(0.03, 0.97, f'{model_name}\n(z={z_coord})', color='white',
                horizontalalignment='left', verticalalignment='top', transform=ax.transAxes)

        # Overlay the corresponding heatmap.
        im = ax.imshow(ndimage.rotate(heatmap[:, :, z_coord], 90), cmap=overlay_cmap,
                       vmin=local_vmin, vmax=local_vmax, interpolation=None, alpha=0.7)

        # Add an independent colorbar with appropriate scaling.
        cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        cbar.ax.tick_params(labelsize=7)

    # Add the coronal view subplot: take the middle slice along the y-axis (coronal view with shape (x, z)).
    ax_cor = fig.add_subplot(gs[-1, :])  # Occupies the last row across all columns.
    ax_cor.axis('off')

    # Get the middle coronal slice.
    mid_y = img_npy.shape[1] // 2
    coronal_slice = img_npy[:, mid_y, :]  # Shape (x, z)

    # Rotate 90° so that the vertical axis represents the z coordinate (from bottom to top).
    ax_cor.imshow(ndimage.rotate(coronal_slice, 90), cmap=cmap, vmin=vmin, vmax=vmax, interpolation=None)

    # Since the current z coordinate is computed from the top of the brain,
    # reverse the z coordinate so that z=0 corresponds to the bottom:
    max_z = img_npy.shape[2] - 1
    reversed_z = max_z - z_coord

    # Draw a horizontal red dashed line on the coronal view to indicate the current transverse (z) slice position
    # (calculated from the bottom).
    ax_cor.axhline(y=reversed_z, color='red', linestyle='--', linewidth=2)
    ax_cor.set_title(f"Coronal view (mid y={mid_y})\nRed line indicates z={z_coord} (bottom-up)")

    plt.show()



def interactive_slider_with_coronal(img_npy, heatmaps, overlay_cmap='hot', **plot_kwargs):
    """
    Interactive Z-slice viewer for axial heatmaps with a coronal reference.
    NOTE: VBM-SVM heatmap is smoothed (Gaussian, sigma=1) by default.
    """
    import ipywidgets as widgets
    from IPython.display import display
    from matplotlib import pyplot as plt

    max_z = img_npy.shape[2] - 1
    z_slider = widgets.IntSlider(
        value=max_z // 2, min=0, max=max_z, step=1, description="Z Slice"
    )
    output = widgets.Output()

    def update_plot(z_coord):
        with output:
            output.clear_output(wait=True)

            # Always smooth VBM-SVM before plotting
            from scipy.ndimage import gaussian_filter
            heatmaps_proc = {}
            for model_name, hm in heatmaps.items():
                if model_name == "VBM-SVM":
                    hm_smooth = gaussian_filter(hm, sigma=1, mode='constant', cval=0.0)
                    # Re-apply mask to avoid spreading outside brain
                    hm_smooth = np.where(img_npy != 0, hm_smooth, 0)
                    heatmaps_proc[model_name] = hm_smooth
                else:
                    heatmaps_proc[model_name] = hm

            # Call plotting function
            plot_transverse_heatmaps_with_coronal(
                img_npy,
                heatmaps_proc,
                z_coord,
                overlay_cmap=overlay_cmap,
                **plot_kwargs
            )
            plt.close('all')

    ui = widgets.interactive_output(update_plot, {'z_coord': z_slider})
    display(z_slider, output)
    update_plot(z_slider.value)  # initial draw


# Interactive slider for coronal browsing (Y axis), with VBM-SVM smoothing hard-coded
def interactive_slider_with_axial(img_npy, heatmaps, overlay_cmap='hot', **plot_kwargs):
    """
    Interactive slider for browsing coronal slices (y axis) with heatmaps,
    using plot_coronal_heatmaps_with_axial().
    NOTE: VBM-SVM is always smoothed (sigma=1) internally in the plotting function.
    """
    import ipywidgets as widgets
    from IPython.display import display
    from matplotlib import pyplot as plt

    max_y = img_npy.shape[1] - 1
    y_slider = widgets.IntSlider(
        value=max_y // 2, min=0, max=max_y, step=1, description="Y Slice"
    )
    output = widgets.Output()

    def update_plot(y_coord):
        with output:
            output.clear_output(wait=True)
            plot_coronal_heatmaps_with_axial(
                img_npy, heatmaps, y_coord, overlay_cmap=overlay_cmap, **plot_kwargs
            )
            plt.close('all')

    ui = widgets.interactive_output(update_plot, {'y_coord': y_slider})
    display(y_slider, output)
    update_plot(y_slider.value)  # initial draw


def generate_gif(img_npy, heatmaps, overlay_cmap, filename='output.gif', delay=0.5, step=1):
    """
    Generate a GIF by iterating through the z slices of the 3D image.

    Parameters:
    - img_npy: 3D array (base anatomical image)
    - heatmaps: Dictionary {model_name: 3D heatmap array}
    - overlay_cmap: Colormap for the overlay heatmaps
    - filename: Output filename for the GIF
    - delay: Time delay between frames (in seconds)
    - step: Step size to iterate through z slices (e.g., 1 means every slice)
    """
    frames = []
    max_z = img_npy.shape[2] - 1
    for z_coord in range(0, max_z + 1, step):
        # Generate the figure for the current z slice without displaying it.
        fig = plot_transverse_heatmaps_with_coronal(img_npy, heatmaps, z_coord, overlay_cmap=overlay_cmap, show=False)

        # Save the figure to a buffer.
        buf = io.BytesIO()
        fig.savefig(buf, format='png')
        buf.seek(0)
        image = imageio.imread(buf)
        frames.append(image)
        plt.close(fig)

    # Save all frames as a GIF.
    imageio.mimsave(filename, frames, duration=delay)
    print(f"GIF saved as {filename}")

def generate_gif(
    img_npy,
    heatmaps,
    overlay_cmap,
    filename='output.gif',
    delay=0.5,
    step=1
):
    """
    Generate a looping GIF by iterating through z slices of a 3D image.

    Parameters
    ----------
    img_npy : np.ndarray
        3D anatomical image array.
    heatmaps : dict
        Dictionary {model_name: 3D heatmap array}.
    overlay_cmap : str or Colormap
        Colormap for the overlay heatmaps.
    filename : str
        Output GIF filename.
    delay : float
        Delay between frames (seconds).
    step : int
        Step size to skip slices (1 = every slice).
    """
    import io
    import imageio.v2 as imageio
    import matplotlib.pyplot as plt

    frames = []
    max_z = img_npy.shape[2] - 1

    for z_coord in range(0, max_z + 1, step):
        # Create the figure for this z slice without showing it
        fig = plot_transverse_heatmaps_with_coronal(
            img_npy,
            heatmaps,
            z_coord,
            overlay_cmap=overlay_cmap,
            show=False
        )

        # Save to buffer
        buf = io.BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight', pad_inches=0, dpi=100)
        buf.seek(0)
        frame = imageio.imread(buf)
        frames.append(frame)

        buf.close()
        plt.close(fig)

    # Save all frames as a looping GIF (loop=0 → infinite)
    imageio.mimsave(filename, frames, duration=delay, loop=0)
    print(f"Looping GIF saved as: {filename}")




def plot_transverse_heatmaps_with_coronal(
    img_npy,
    heatmaps,
    z_coord,
    cmap='gray',
    vmin=None,
    vmax=None,
    overlay_cmap='hot',
    overlay_vmin=None,
    overlay_vmax=None,
    max_cols=4,
    wspace=0.15,
    hspace=0.0,
    cbar_fraction=0.035,
    cbar_pad=0.005,
    show=True
):
    """
    Plot transverse (axial) slices with overlay heatmaps and a coronal reference slice.
    For VBM-SVM:
      - remove isolated single voxels (connectivity=1)
      - keep image normalization as-is (data-driven)
      - draw a separate colorbar normalized to p-value [0, 0.05]
    """
    import math
    import numpy as np
    import matplotlib.pyplot as plt
    from matplotlib.gridspec import GridSpec
    from matplotlib import colors as mcolors
    from scipy import ndimage

    num_models = len(heatmaps)
    total_plots = num_models + 1  # +1 for coronal reference

    ncols = min(total_plots, max_cols)
    nrows = math.ceil(total_plots / ncols)

    fig = plt.figure(figsize=(ncols * 3, nrows * 3.6))
    gs = GridSpec(nrows, ncols, figure=fig)
    plt.subplots_adjust(wspace=wspace, hspace=hspace)

    axes = [fig.add_subplot(gs[i // ncols, i % ncols]) for i in range(total_plots)]
    for i in range(total_plots, nrows * ncols):
        fig.add_subplot(gs[i // ncols, i % ncols]).axis('off')

    brain_mask = (img_npy != 0)

    # --- Axial heatmaps ---
    for i, (model_name, heatmap) in enumerate(heatmaps.items()):
        ax = axes[i]
        ax.axis('off')

        # Re-mask to brain
        heatmap_filter = np.where(brain_mask, heatmap, 0)

        # VBM-SVM: remove isolated single voxels
        if model_name == "VBM-SVM":
            overlay_01 = heatmap_filter.copy()
            bin_mask = overlay_01 > 0
            bin_mask_clean = remove_single_voxels(bin_mask, connectivity=1)
            removed = int(bin_mask.sum() - bin_mask_clean.sum())
            #print("removed single-voxel sites:", removed)
            display_overlay = overlay_01 * bin_mask_clean
        else:
            display_overlay = heatmap_filter

        # Data-driven normalization (do not clamp to 0.05)
        if overlay_vmin is None or overlay_vmax is None:
            valid = display_overlay[brain_mask]
            if valid.size > 0 and np.isfinite(valid).any():
                local_vmin = float(np.nanmin(valid))
                local_vmax = float(np.nanmax(valid))
                if (not np.isfinite(local_vmin)) or (not np.isfinite(local_vmax)) or (local_vmin == local_vmax):
                    local_vmin, local_vmax = 0.0, 1.0
            else:
                local_vmin, local_vmax = 0.0, 1.0
        else:
            local_vmin, local_vmax = overlay_vmin, overlay_vmax

        base_rot = ndimage.rotate(img_npy[:, :, z_coord], 90)
        hm_rot   = ndimage.rotate(display_overlay[:, :, z_coord], 90)

        ax.imshow(base_rot, vmin=vmin, vmax=vmax, cmap=cmap, origin='upper')
        ax.text(0.03, 0.97, f'{model_name}\n(z={z_coord})', color='white',
                ha='left', va='top', transform=ax.transAxes)

        # Image overlay uses data-driven vmin/vmax
        im = ax.imshow(hm_rot, cmap=overlay_cmap,
                       vmin=local_vmin, vmax=local_vmax, alpha=0.7, origin='upper')

        # Colorbar
        if model_name == "VBM-SVM":
            # Separate mappable with fixed Normalize(0, 0.05)
            mappable = plt.cm.ScalarMappable(norm=mcolors.Normalize(0.0, 0.05),
                                             cmap=overlay_cmap)
            mappable.set_array([])
            cbar = fig.colorbar(mappable, ax=ax, fraction=cbar_fraction, pad=cbar_pad)
            cbar.set_label("p-value (0 to 0.05)", rotation=90)
            cbar.set_ticks([0.00, 0.01, 0.02, 0.03, 0.04, 0.05])
            cbar.ax.tick_params(labelsize=7)
        else:
            cbar = fig.colorbar(im, ax=ax, fraction=cbar_fraction, pad=cbar_pad)
            cbar.ax.tick_params(labelsize=7)

    # --- Coronal reference ---
    ax_cor = axes[-1]
    ax_cor.axis('off')
    mid_y = img_npy.shape[1] // 2
    coronal_slice = img_npy[:, mid_y, :]  # (x, z)
    cor_rot = ndimage.rotate(coronal_slice, 90)
    ax_cor.imshow(cor_rot, cmap=cmap, vmin=vmin, vmax=vmax, origin='upper')

    y_disp = cor_rot.shape[0] - 1 - z_coord
    ax_cor.axhline(y=y_disp, color='red', linestyle='--', linewidth=2)
    ax_cor.set_title(f"Coronal ref (y={mid_y})\nred line: z={z_coord}", fontsize=9)

    if show:
        plt.show()
    else:
        return fig




def plot_coronal_heatmaps_with_axial(
    img_npy,
    heatmaps,
    y_coord,
    cmap='gray',
    vmin=None,
    vmax=None,
    overlay_cmap='hot',
    overlay_vmin=None,
    overlay_vmax=None,
    max_cols=4,
    reference_z=None,
    wspace=0.15,
    hspace=0.0,
    cbar_fraction=0.035,
    cbar_pad=0.005,
    show=True
):
    """
    Plot coronal slices with overlay heatmaps and an axial reference slice.
    Rotation (90 deg) is kept for display.
    NOTE: y index is assumed to run from posterior (small) to anterior (large).
          The axial reference maps y so that larger y appears higher (toward anterior).

    Hard-coded special case:
      - If model name is "VBM-SVM", its heatmap is Gaussian-smoothed (sigma=1)
        and re-masked to avoid spill outside the brain.
    """
    import math
    import numpy as np
    import matplotlib.pyplot as plt
    from matplotlib.gridspec import GridSpec
    from scipy import ndimage
    from scipy.ndimage import gaussian_filter

    num_models = len(heatmaps)
    total_plots = num_models + 1  # +1 for axial reference

    ncols = min(total_plots, max_cols)
    nrows = math.ceil(total_plots / ncols)

    fig = plt.figure(figsize=(ncols * 3, nrows * 3.6))
    gs = GridSpec(nrows, ncols, figure=fig)
    plt.subplots_adjust(wspace=wspace, hspace=hspace)

    axes = [fig.add_subplot(gs[i // ncols, i % ncols]) for i in range(total_plots)]
    # Hide unused slots
    for i in range(total_plots, nrows * ncols):
        fig.add_subplot(gs[i // ncols, i % ncols]).axis('off')

    if reference_z is None:
        reference_z = img_npy.shape[2] // 2

    brain_mask = (img_npy != 0)

    # ---- Coronal overlays ----
    for i, (model_name, heatmap) in enumerate(heatmaps.items()):
        ax = axes[i]
        ax.axis('off')

        # Hard-coded smoothing for VBM-SVM only
        if model_name == "VBM-SVM":
            hm_proc = gaussian_filter(heatmap, sigma=1, mode='constant', cval=0.0)
        else:
            hm_proc = heatmap

        # Re-apply brain mask after smoothing
        heatmap_filter = np.where(brain_mask, hm_proc, 0)

        # Per-slice vmin/vmax if not provided
        if overlay_vmin is None or overlay_vmax is None:
            valid = heatmap_filter[brain_mask]
            local_vmin = float(valid.min()) if valid.size > 0 else 0.0
            local_vmax = float(valid.max()) if valid.size > 0 else 1.0
        else:
            local_vmin, local_vmax = overlay_vmin, overlay_vmax

        # Coronal slice at y = y_coord: shape (x, z)
        coronal_base = img_npy[:, y_coord, :]
        coronal_overlay = heatmap_filter[:, y_coord, :]

        # Keep 90° rotation for display; keep matplotlib default origin='upper'
        base_rot = ndimage.rotate(coronal_base, 90)
        overlay_rot = ndimage.rotate(coronal_overlay, 90)

        ax.imshow(base_rot, vmin=vmin, vmax=vmax, cmap=cmap, origin='upper')
        ax.text(0.03, 0.97, f'{model_name}\n(y={y_coord})', color='white',
                ha='left', va='top', transform=ax.transAxes)

        im = ax.imshow(overlay_rot, cmap=overlay_cmap,
                       vmin=local_vmin, vmax=local_vmax, alpha=0.7, origin='upper')

        cbar = fig.colorbar(im, ax=ax, fraction=cbar_fraction, pad=cbar_pad)
        cbar.ax.tick_params(labelsize=7)

    # ---- Axial reference (z = reference_z) ----
    ax_ref = axes[-1]
    ax_ref.axis('off')

    # Axial slice: shape (x, y)
    axial_base = img_npy[:, :, reference_z]

    # Rotate 90° for display; with origin='upper', row index 0 is top.
    axial_rot = ndimage.rotate(axial_base, 90)
    ax_ref.imshow(axial_rot, cmap=cmap, vmin=vmin, vmax=vmax, origin='upper')

    # Map array y index to display row so that larger y (more anterior) draws higher.
    y_disp = axial_rot.shape[0] - 1 - y_coord
    ax_ref.axhline(y=y_disp, color='red', linestyle='--', linewidth=2)

    ax_ref.set_title(f"Axial ref (z={reference_z})\nred line: y={y_coord}", fontsize=9)

    if show:
        plt.show()
    else:
        return fig




def plot_coronal_heatmaps_with_axial(
    img_npy,
    heatmaps,
    y_coord,
    cmap='gray',
    vmin=None,
    vmax=None,
    overlay_cmap='hot',
    overlay_vmin=None,
    overlay_vmax=None,
    max_cols=4,
    reference_z=None,
    wspace=0.15,
    hspace=0.0,
    cbar_fraction=0.035,
    cbar_pad=0.005,
    show=True
):
    """
    Plot coronal slices with overlay heatmaps and an axial reference slice.
    For VBM-SVM:
      - remove isolated single voxels (connectivity=1)
      - keep image normalization as-is (data-driven)
      - draw a separate colorbar normalized to p-value [0, 0.05]
    """
    import math
    import numpy as np
    import matplotlib.pyplot as plt
    from matplotlib.gridspec import GridSpec
    from matplotlib import colors as mcolors
    from scipy import ndimage

    num_models = len(heatmaps)
    total_plots = num_models + 1  # +1 for axial reference

    ncols = min(total_plots, max_cols)
    nrows = math.ceil(total_plots / ncols)

    fig = plt.figure(figsize=(ncols * 3, nrows * 3.6))
    gs = GridSpec(nrows, ncols, figure=fig)
    plt.subplots_adjust(wspace=wspace, hspace=hspace)

    axes = [fig.add_subplot(gs[i // ncols, i % ncols]) for i in range(total_plots)]
    for i in range(total_plots, nrows * ncols):
        fig.add_subplot(gs[i // ncols, i % ncols]).axis('off')

    if reference_z is None:
        reference_z = img_npy.shape[2] // 2

    brain_mask = (img_npy != 0)

    # ---- Coronal overlays ----
    for i, (model_name, heatmap) in enumerate(heatmaps.items()):
        ax = axes[i]
        ax.axis('off')

        # Re-mask to brain
        heatmap_filter = np.where(brain_mask, heatmap, 0)

        # VBM-SVM: remove isolated single voxels
        if model_name == "VBM-SVM":
            overlay_01 = heatmap_filter.copy()
            bin_mask = overlay_01 > 0
            bin_mask_clean = remove_single_voxels(bin_mask, connectivity=1)
            removed = int(bin_mask.sum() - bin_mask_clean.sum())
            #print("removed single-voxel sites:", removed)
            display_overlay = overlay_01 * bin_mask_clean
        else:
            display_overlay = heatmap_filter

        # Data-driven normalization (do not clamp to 0.05)
        if overlay_vmin is None or overlay_vmax is None:
            valid = display_overlay[brain_mask]
            if valid.size > 0 and np.isfinite(valid).any():
                local_vmin = float(np.nanmin(valid))
                local_vmax = float(np.nanmax(valid))
                if (not np.isfinite(local_vmin)) or (not np.isfinite(local_vmax)) or (local_vmin == local_vmax):
                    local_vmin, local_vmax = 0.0, 1.0
            else:
                local_vmin, local_vmax = 0.0, 1.0
        else:
            local_vmin, local_vmax = overlay_vmin, overlay_vmax

        # Extract slices
        coronal_base = img_npy[:, y_coord, :]
        coronal_overlay = display_overlay[:, y_coord, :]

        base_rot = ndimage.rotate(coronal_base, 90)
        overlay_rot = ndimage.rotate(coronal_overlay, 90)

        ax.imshow(base_rot, vmin=vmin, vmax=vmax, cmap=cmap, origin='upper')
        ax.text(0.03, 0.97, f'{model_name}\n(y={y_coord})', color='white',
                ha='left', va='top', transform=ax.transAxes)

        im = ax.imshow(
            overlay_rot,
            cmap=overlay_cmap,
            vmin=local_vmin, vmax=local_vmax,
            alpha=0.7, origin='upper'
        )

        # Colorbar
        if model_name == "VBM-SVM":
            from matplotlib import colors as mcolors
            mappable = plt.cm.ScalarMappable(norm=mcolors.Normalize(0.0, 0.05),
                                             cmap=overlay_cmap)
            mappable.set_array([])
            cbar = fig.colorbar(mappable, ax=ax, fraction=cbar_fraction, pad=cbar_pad)
            cbar.set_label("p-value (0 to 0.05)", rotation=90)
            cbar.set_ticks([0.00, 0.01, 0.02, 0.03, 0.04, 0.05])
            cbar.ax.tick_params(labelsize=7)
        else:
            cbar = fig.colorbar(im, ax=ax, fraction=cbar_fraction, pad=cbar_pad)
            cbar.ax.tick_params(labelsize=7)

    # ---- Axial reference (z = reference_z) ----
    ax_ref = axes[-1]
    ax_ref.axis('off')

    axial_base = img_npy[:, :, reference_z]
    axial_rot = ndimage.rotate(axial_base, 90)
    ax_ref.imshow(axial_rot, cmap=cmap, vmin=vmin, vmax=vmax, origin='upper')

    y_disp = axial_rot.shape[0] - 1 - y_coord
    ax_ref.axhline(y=y_disp, color='red', linestyle='--', linewidth=2)
    ax_ref.set_title(f"Axial ref (z={reference_z})\nred line: y={y_coord}", fontsize=9)

    if show:
        plt.show()
    else:
        return fig

# Define color lists for the colormaps.
# The following line defines the active color list.
colors = ['black', 'blue', 'orange', 'gold', 'tomato', 'red']

# Alternative color list can be:
# colors = ['blue', 'green', 'black', 'gold', 'red']

# Create a ListedColormap using the specified colors.
color_list = ListedColormap(colors)

# Create a LinearSegmentedColormap from the list of colors.
mycmap = LinearSegmentedColormap.from_list('mycmap', colors)

# Load the brain atlas used in this study which functioned as the backgroud of heatmaps
#img_seg = "/content/drive/MyDrive/aparcaseg_in_MNI.nii.gz" #Automatic Subcortical Segmentation
#img_seg = nib.load(img_seg).get_fdata()
#img_npy = np.array(img_seg)

img_seg = "/content/T1brain_in_MNI.nii.gz" #T1 brain template
img_seg = nib.load(img_seg).get_fdata()
img_npy = np.array(img_seg)
print(img_npy.shape)

# Crop the segmentation image to the region of interest.
img_npy = img_npy[15:165,20:200,15:165]

# Calculate the midpoint along the first axis (used for splitting hemispheres).
mid_slice = img_npy.shape[0] // 2

# Split the image into left and right hemispheres.
left_hemisphere = img_npy[:mid_slice, :, :]
right_hemisphere = img_npy[mid_slice:, :, :]

# Normalize the intensities of each hemisphere independently.
left_norm = (left_hemisphere - np.min(left_hemisphere)) / (np.max(left_hemisphere) - np.min(left_hemisphere))
right_norm = (right_hemisphere - np.min(right_hemisphere)) / (np.max(right_hemisphere) - np.min(right_hemisphere))

# Concatenate the normalized left and right hemispheres back together along the first axis.
img_npy = np.concatenate((left_norm, right_norm), axis=0)

# Load the absolute values of various heatmap arrays from .npy files.
heatmap_GLCNN = abs(np.load("/content/GLCNN_OCC_ADCN_ADNI.npy"))
heatmap_VGG = abs(np.load("/content/VGG_OCC_ADCN_ADNI.npy"))
heatmap_DenseNet = abs(np.load("/content/DenseNet_OCC_ADCN_ADNI.npy"))
heatmap_Vol_EBM = abs(np.load("/content/VolEBM_ADCN_ADNI.npy"))
heatmap_Vol_SVM = abs(np.load("/content/VolSVM_wmap_ADCN_ADNI.npy"))
heatmap_VBM_SVM = abs(np.load("/content/VBMSVM_pmap_ADCN_ADNI.npy"))
heatmap_ICNN_EBM = abs(np.load("/content/ICNN_ADCN_ADNI.npy"))
heatmap_ICNN_IGANN = abs(np.load("/content/ICNN-IGANN_ADCN_ADNI.npy"))
heatmap_ICNN_NAM = abs(np.load("/content/ICNN-NAM_ADCN_ADNI.npy"))
heatmap_ConvNext = abs(np.load("/content/ConvNext_OCC_ADCN_ADNI.npy"))




# Set heatmap values to zero wherever the corresponding anatomical image (img_npy) is zero.
# This masks out non-brain areas or background regions.
heatmap_GLCNN = np.where(img_npy == 0, 0, heatmap_GLCNN)
heatmap_VGG = np.where(img_npy == 0, 0, heatmap_VGG)
heatmap_DenseNet = np.where(img_npy == 0, 0, heatmap_DenseNet)
heatmap_VBM_SVM = np.where(img_npy == 0, 0, heatmap_VBM_SVM)
heatmap_ICNN_EBM = np.where(img_npy == 0, 0, heatmap_ICNN_EBM)
heatmap_ICNN_IGANN = np.where(img_npy == 0, 0, heatmap_ICNN_IGANN)
heatmap_ICNN_NAM = np.where(img_npy == 0, 0, heatmap_ICNN_NAM)
heatmap_ConvNext = np.where(img_npy == 0, 0, heatmap_ConvNext)

# Organize the heatmaps into a dictionary with model names as keys.
heatmaps = {
    "GLCNN": heatmap_GLCNN,
    "VGG": heatmap_VGG,
    "DenseNet": heatmap_DenseNet,
    "ConvNext":heatmap_ConvNext,
    "Vol-EBM": heatmap_Vol_EBM,
    "Vol-SVM": heatmap_Vol_SVM,
    "VBM-SVM": heatmap_VBM_SVM,
    "ICNN-EBM": heatmap_ICNN_EBM,
    "ICNN-IGANN": heatmap_ICNN_IGANN,
    "ICNN-NAM": heatmap_ICNN_NAM,

}

# Run the interactive UI using the custom colormap (mycmap) to overlay the heatmaps on the anatomical image.
#interactive_slider(img_npy, heatmaps, overlay_cmap=mycmap)
# Run the interactive UI using the custom colormap (mycmap) to overlay the heatmaps on the anatomical image.
interactive_slider_with_coronal(img_npy, heatmaps, overlay_cmap=mycmap)
interactive_slider_with_axial(img_npy, heatmaps, overlay_cmap=mycmap)

###Output and show a GIF
import io
import imageio

generate_gif(img_npy, heatmaps, overlay_cmap=mycmap, filename='output.gif', delay=0.3, step=3)
display(Image(filename="output.gif"))

